[package]
name = "poker-rust-kata"
version = "0.1.0"
authors = ["Fabio Elizandro <fabio@elizandro.com.br>"]

[dependencies]
poker-parser = { path = "crates/poker-parser" }
poker-dealer = { path = "crates/poker-dealer" }
